x-postgress-variables: &postgress-variables
  POSTGRES_DB: "${POSTGRES_DB:-postgres}"
  POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-q3opc3123§§!'urbn$5(#6}"

x-envs: &envs
  MODE: prod
  ALLOWED_HOST: "${ALLOWED_HOST}"
  ELN_URL: "${ELN_URL}"
  DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
  DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
  DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db

services:
  db:
    image: postgres:13
    restart: unless-stopped
    hostname: db
    expose:
      - 5432
    ports:
      - ${PROJECT_POSTGRES_PORT:-65432}:5432
    environment:
      <<: *postgress-variables
    volumes:
      - bridge_db:/var/lib/postgresql/data/
  web:
    image: mstarman/shuttlebuilder:0.2.11
    restart: unless-stopped
    depends_on:
      - db
    environment:
      <<: [*envs, *postgress-variables]
    ports:
      - ${PROJECT_WEB_PORT:-80}:80
volumes:
  bridge_db:
