version: '3'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    hostname: db
    expose:
      - 5432
    ports:
      - ${DJANGO_POSTGRES_PORT:-65432}:5432
    environment:
      - POSTGRES_USER=${DJANGO_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DJANGO_POSTGRES_NAME}
    env_file:
      - ./.env
    volumes:
      - bridge_db:/var/lib/postgresql/data/
  web:
    build:
      context: .
    image: mstarman/shuttlebuilder:0.2.1
    depends_on:
      - db
    environment:
      - DJANGO_POSTGRES_PORT=5432
      - DJANGO_POSTGRES_HOST=db
    env_file:
      - ./.env
    ports:
      - 3222:80
volumes:
  bridge_db:
