# Generated by Django 5.0.4 on 2024-05-14 11:13

import sdc_core.sdc_extentions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElnConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Eln connection!')),
                ('active', models.BooleanField()),
                ('token', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('device', models.IntegerField(default=0)),
            ],
            bases=(models.Model, sdc_core.sdc_extentions.models.SdcModel),
        ),
    ]
