# Generated by Django 5.0.6 on 2024-05-15 11:27

import sdc_core.sdc_extentions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_elnuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the git repo. This name cannot be changed!', max_length=50, unique=True)),
                ('url', models.CharField(help_text='URL to the git repo.', max_length=255)),
                ('branch', models.CharField(default='main', help_text='Enter the branch name or commit ID.', max_length=255, verbose_name='Commit Or Branch')),
                ('is_active', models.BooleanField(default=False)),
                ('last_reload', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(models.Model, sdc_core.sdc_extentions.models.SdcModel),
        ),
    ]
