# Generated by Django 5.0.6 on 2024-05-15 15:47

import django.utils.timezone
import sdc_core.sdc_extentions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_gitinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the EFW instance. This name cannot be changed!', max_length=50, unique=True)),
                ('user', models.CharField(default='', help_text='WebDAV or STFP User', max_length=50)),
                ('password', models.CharField(help_text='WebDAV or STFP Password', max_length=100)),
                ('transfer', models.CharField(choices=[('webdav', 'WebDAV'), ('sftp', 'SFTP')], default='webdav', help_text='You can either use the WebDAV protocol or the SFTP protocol', max_length=255, verbose_name='Transfer protocol')),
                ('src', models.CharField(help_text='Source directory to monitor. Note: If you use only single \\ in the path, the build will fail. Therefore, make sure that you always use \\\\.', max_length=255)),
                ('dst', models.CharField(help_text='WebDAV or SFTP destination URL. If the destination is on the lsdf, the URL should be as follows:<br>\n        <span style="margin-left: 20px; font-weight: 800;">SFTP</span>: os-login.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>\n        <span style="margin-left: 20px; font-weight: 800;">WebDAV</span>: https://os-webdav.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>\n\n                    <span style="margin-left: 30px;">[OE]-Organisationseinheit, z.B. kit.</span><br>\n                    <span style="margin-left: 30px;">[inst]-Institut-Name, z.B. ioc, scc, ikp, imk-asf etc.</span><br>\n                    <span style="margin-left: 30px;">[USERNAME]-User-Name z.B. xy1234, bs_abcd etc.</span><br>\n                    <span style="margin-left: 30px;">[PROJECT_PATH]-Path (directory) within the LSDF</span>', max_length=255)),
                ('efw_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder'), ('zip', 'ZIP')], help_text="Type must be 'file', 'folder' or 'zip'. The 'file' option means that each file is handled individually, the 'folder' option means that entire folders are transmitted only when all files in them are ready. The option 'zip' sends a folder zipped, only when all files in a folder are ready.", max_length=255, verbose_name='Type')),
                ('duration', models.IntegerField(default=300, help_text='Duration in seconds, i.e., how long a file must not be changed before sent. (default 300 sec.)')),
                ('architecture', models.CharField(choices=[('win_i386', 'Windows i386'), ('win_64', 'Windows 64 Bit'), ('ubuntu_64', 'Ubuntu 64 Bit')], default='win_i386', help_text='Your computer architecture : either 64 bit or 32 bit (i386) ', max_length=255, verbose_name='System architecture')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_build', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(models.Model, sdc_core.sdc_extentions.models.SdcModel),
        ),
    ]
