# Generated by Django 5.1.2 on 2024-10-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_shuttleinstance_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="shuttleinstance",
            name="common_prefix",
            field=models.IntegerField(
                default=0,
                help_text="Type must be 'file', 'folder', 'tar' or 'zip'. The 'file' option means that each file is handled individually, the 'folder' option means that entire folders are transmitted only when all files in them are ready. The options 'tar' ond/or 'zip' sends a folder zipped (or compressed as tar archieve), only when all files in a folder are ready.",
                verbose_name="Common prefix",
            ),
        ),
        migrations.AlterField(
            model_name="gitinstance",
            name="url",
            field=models.CharField(
                default="", help_text="URL to the git repo.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="shuttleinstance",
            name="shuttle_type",
            field=models.CharField(
                choices=[
                    ("file", "File"),
                    ("folder", "Folder"),
                    ("zip", "ZIP"),
                    ("tar", "TAR"),
                    ("flat_tar", "Flat TAR"),
                ],
                help_text="Type must be 'file', 'folder', 'tar' or 'zip'. The 'file' option means that each file is handled individually, the 'folder' option means that entire folders are transmitted only when all files in them are ready. The options 'tar' ond/or 'zip' sends a folder zipped (or compressed as tar archieve), only when all files in a folder are ready.",
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
