# Generated by Django 5.1.2 on 2024-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main_app",
            "0007_shuttleinstance_common_prefix_alter_gitinstance_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shuttleinstance",
            name="common_prefix",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Type must be 'file', 'folder', 'tar' or 'zip'. The 'file' option means that each file is handled individually, the 'folder' option means that entire folders are transmitted only when all files in them are ready. The options 'tar' ond/or 'zip' sends a folder zipped (or compressed as tar archieve), only when all files in a folder are ready.",
                verbose_name="Common prefix",
            ),
        ),
        migrations.AlterField(
            model_name="shuttleinstance",
            name="duration",
            field=models.PositiveIntegerField(
                default=300,
                help_text="Duration in seconds, i.e., how long a file must not be changed before sent. (default 300 sec.)",
            ),
        ),
    ]
