# Generated by Django 5.1.2 on 2024-10-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_alter_shuttleinstance_common_prefix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shuttleinstance",
            name="common_prefix",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The common prefix length is only required if the type is flat_tar. This value specifies the number of leading characters that must be the same in order for files to be packed together.",
                verbose_name="Common prefix length",
            ),
        ),
    ]
