# Generated by Django 5.1.4 on 2024-12-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_rename_common_prefix_shuttleinstance_common_name_parts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shuttleinstance",
            name="common_name_parts",
            field=models.CharField(
                default="^[A-Za-z]{1,4}",
                help_text="The common prefix length is only required if the type is flat_tar. This value specifies the number of leading characters that must be the same in order for files to be packed together.",
                max_length=255,
                verbose_name="Common name regex",
            ),
        ),
    ]
