# Generated by Django 5.2.9 on 2025-12-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_shuttleinstance_common_name_parts_value'),
    ]

    operations = [
    ]
