# Generated by Django 5.2.9 on 2025-12-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_migrate_old_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttleinstance',
            name='architecture',
            field=models.CharField(choices=[('win_i386', 'Windows i386'), ('win_64', 'Windows 64 Bit'), ('ubuntu_64', 'Ubuntu 64 Bit'), ('raspberry_pi_6', 'Raspberry Pi ARMv6'), ('raspberry_pi_7', 'Raspberry Pi ARMv7'), ('raspberry_pi_64', 'Raspberry Pi ARM 64 Bit')], default='win_i386', help_text='Your computer architecture : either 64 bit, i386 or ARM And your OS: Linux or Windows', max_length=255, verbose_name='System architecture'),
        ),
        migrations.AlterField(
            model_name='shuttleinstance',
            name='common_name_parts',
            field=models.CharField(blank=True, default='^[A-Za-z]{1,4}', help_text='The regex for the common name is used to collect all files that belong to the same data set. This value is only used if the type is flat tar. All files that either have the same regex group resolutions or (if you do not use groups) have the same global result are archived together<this.render_help></this.render_help>', max_length=255, verbose_name='Common name regex'),
        ),
        migrations.AlterField(
            model_name='shuttleinstance',
            name='src',
            field=models.CharField(help_text='Source directory to monitor.', max_length=255),
        ),
    ]
