# Generated by Django 5.2.9 on 2026-02-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_shuttleinstance_architecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttleinstance',
            name='dst_bagit',
            field=models.CharField(blank=True, help_text='WebDAV or SFTP destination URL. If the destination is on the lsdf, the URL should be as follows:<br>\n            <span style="margin-left: 20px; font-weight: 800;">SFTP</span>: os-login.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>\n            <span style="margin-left: 20px; font-weight: 800;">WebDAV</span>: https://os-webdav.lsdf.kit.edu/[OE]/[inst]/projects/[PROJECT_PATH]/<br>\n\n                        <span style="margin-left: 30px;">[OE]-Organisationseinheit, z.B. kit.</span><br>\n                        <span style="margin-left: 30px;">[inst]-Institut-Name, z.B. ioc, scc, ikp, imk-asf etc.</span><br>\n                        <span style="margin-left: 30px;">[USERNAME]-User-Name z.B. xy1234, bs_abcd etc.</span><br>\n                        <span style="margin-left: 30px;">[PROJECT_PATH]-Path (directory) within the LSDF</span>', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shuttleinstance',
            name='passwort_bagit',
            field=models.CharField(blank=True, help_text='WebDAV or STFP Password for converted Bagit', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shuttleinstance',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='shuttleinstance',
            name='user_bagit',
            field=models.CharField(blank=True, help_text='WebDAV or STFP User for converted Bagit', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shuttleinstance',
            name='with_converter',
            field=models.BooleanField(default=False, help_text='Check whether the raw file needs to be stored in Chomtion, or if storing only the converted BagIt archive is sufficient. If checked, you must specify two destinations: the already configured destination is used for the raw data file, and the additional input below is used for the BagIt archive (Chemotion).', verbose_name='With converter'),
        ),
    ]
