# Generated by Django 5.2.11 on 2026-02-04 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_shuttleinstance_dst_bagit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttleinstance',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
    ]
