# Generated by Django 5.2.11 on 2026-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_shuttleinstance_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttleinstance',
            name='public_link',
            field=models.URLField(blank=True, help_text='The prefix of the publicly accessible link to the raw files. It must include the scheme, domain, and path (e.g. https://your-file-storage-example.eu/data/raw/). Only the file name is appended.', null=True),
        ),
    ]
